name: Gradr

on:
  pull_request:
    branches:
      - master

jobs:
  ch-1:
    name: audit challenge 1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [10, 12]
        operating-system: [ubuntu-18.04]
        php: [7.2.12]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Prepare To Install
        uses: actions/checkout@v2
        with:
          version: 10.x
      - name: Install Node dependencies
        run: |
          yarn Install
          yarn add phplint

      - name: Run Audits
        run: yarn phplint './src/**/*.php'

      - name: setup php
        uses: actions/checkout@v1
        with:
          version: ${{ matrix.php }}
      - name: check version
        run: php --version
